name             'package-builder'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures package-builder'
long_description 'Installs/Configures package-builder'
version          '0.1.0'

depends 'php', '>= 1.8.0'
depends 'git', '>= 4.3.7'
depends 'composer', '>= 2.2.1'
depends 'apt', '>= 3.0.0'
depends 'docker', '>= 2.7.1'